"""initial migration

Revision ID: 49f47bd1512f
Revises: 
Create Date: 2022-06-20 21:32:22.007497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f47bd1512f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('comment', 'post_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('comment', 'name')
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('comment', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('comment', 'post_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comment', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
